### ISSUE TITLE
PEP 502 should be given priority

### ISSUE THREAD

**Issue by arekbulski** [syrusakbary/interpy#12]
There is a PEP draft that puts string interpolation into base language. This should take priority over hackish modules. This is a public notice rather than issue.
https://www.python.org/dev/peps/pep-0502/

**Comment by mindw** [comment]
At the very least you should consider who are still using the "ancient" Python 3.5!

And this *is* one of the reference implementations mentioned in your link.

**Comment by arekbulski** [comment]
Oh thank you for explaining. I will close it since it makes no sense anymore.
